### ISSUE TITLE
add make_ext4fs

### ISSUE THREAD

**Issue by Wahyu6070** [Zackptg5/Cross-Compiled-Binaries-Android#1]

**Comment by Zackptg5** [comment]
make_ext4s has been replaced with mke2fs (with symlink mkfs.ext4 to shortcut the ext4 functionality of it). Is there anything specifically you need with make_ext4s that isn't already in mke2fs?

**Comment by Wahyu6070** [comment]
in make_ext4fs there is a context file, can mk2fs create a system.img image?  I want to make a tool and need make_ext4 like https://github.com/erfanoabdi/ErfanGSIs/blob/master/tools/Linux/bin/make_ext4fs

**Comment by Zackptg5** [comment]
Yup. If not using the mkfs.ext4 symlink (i.e. calling mke2fs directly), use `-t ext4` flag.
[Here's the man page for it](http://man7.org/linux/man-pages/man8/mke2fs.8.html)
[There's an example here](https://lists.launchpad.net/ubuntu-phone/msg06041.html) although it differs a bit from what you're looking for

**Comment by Zackptg5** [comment]
Closed due to inactivity - assuming the mke2fs did the trick
