### ISSUE TITLE
Unzip Request

### ISSUE THREAD

**Issue by wahyu6070** [Zackptg5/Cross-Compiled-Binaries-Android#10]
Please add Unzip because Unzip in Busybox is incomplete

**Comment by Zackptg5** [comment]
I'll give it a look and let you know how it goes

**Comment by Zackptg5** [comment]
I don't see much of a use for the extra options here and it hasn't been updated in years. I won't be adding it in but there's an arm compiled version already out there if you want it here: https://forum.xda-developers.com/showthread.php?t=1947612
