### ISSUE TITLE
/data/adb/modules/ccbins/post-fs-data.sh: No such file or directory

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#103]
![SmartSelect_20230915-235707_Termux](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/assets/25366502/4d77edfc-d4af-4d1f-951b-baef8412aa40)
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/12639797/ccbins-verbose.log)

**Comment by diehard88** [comment]
I am also unable to download the strace binary.     

<img width="434" alt="ccbin strace" src="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/assets/25366502/5951ce8a-f319-4971-b49e-0c7d0bdeed8b">

attached is the corresponding  ccbin-verbose.log.


[cbins-verbose.log.txt](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/12642355/cbins-verbose.log.txt)

**Comment by diehard88** [comment]
there is no ramdisk, if that matters.

![Screenshot_20230917-043255](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/assets/25366502/c21b3e25-769d-4277-8631-fea31938c1ae)

**Comment by Zackptg5** [comment]
I'm unable to replicate this, can you try reinstalling ccbins?

**Comment by diehard88** [comment]
> I'm unable to replicate this, can you try reinstalling ccbins?

a full reinstallation through the adroicacy module manager brought things back to order.

Before I let you go, one question ...         :)

where are aliases and bashrc now located?

thank very much!

**Comment by Zackptg5** [comment]
> > I'm unable to replicate this, can you try reinstalling ccbins?
> 
> a full reinstallation through the adroicacy module manager brought things back to order.
> 
> Before I let you go, one question ...         :)
> 
> where are aliases and bashrc now located?
> 
> thank very much! 

Main mksh and bash rc files are same location on system (now part of ccbins itself - bashrc included with bash).
All ccbins specific aliases and the universal ones (the .aliases file before) are now system/etc/ccbins-aliases
