### ISSUE TITLE
Aria2 SSL/TLS Handshake Failure

### ISSUE THREAD

**Issue by JeelsBoobz** [Zackptg5/Cross-Compiled-Binaries-Android#104]
**Describe the bug**
Aria2 SSL/TLS handshake failure,, tested for download from gofile.io

**Screenshots**
![IMG_1697369626329](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/assets/38210868/10267249-a21d-4d6c-8f32-53b7b787e1b8)

**Device Info (please complete the following information):**
 - Rom : MIUI 14 Android 12
 - Magisk version : v26.3
 - Other mods installed : No

**Comment by Zackptg5** [comment]
I pushed an update for aria2, see if that fixes it. Did you use static or dynamic build? I recommend dynamic unless you're packaging it into an installer zip
