### ISSUE TITLE
for magisk module，when installing please remove network checking fuction.

### ISSUE THREAD

**Issue by lukemin** [Zackptg5/Cross-Compiled-Binaries-Android#14]
google.com was blocked in China. So It is impossible for people who can not reach google.com to install this amazing module.

**Comment by Zackptg5** [comment]
Is there another website I could use for chinese users that would be guaranteed to be up like google is outside of it?

**Comment by 5c0tt-b0t** [comment]
hey @Zackptg5 "baidu" is a free cloud service from asia, enough storage for releases / changelogs. Hope it helps, your work has helped me many a time!!!

**Comment by Zackptg5** [comment]
That may work. All the network test does is ping the site to make sure you have a network connection since the mod relies on it. I'll take a look at it this week

**Comment by Zackptg5** [comment]
I'm working on an update (should be out this week or next at the latest). I decided to ping github since that's where all the binaries are hosted anyways so that should fix the problem. I'll close this when the next update happens

**Comment by Zackptg5** [comment]
Pushed to testing branch, will be pushed to master within the week
