### ISSUE TITLE
This is bug or not

### ISSUE THREAD

**Issue by cadanganrendy** [Zackptg5/Cross-Compiled-Binaries-Android#16]
Testing internet connection [|] - OK

Fetching available binaries
 [-] - Done

Checking for mod updates
 [/][: 261: unknown operand
 [/][: 14: unknown operand
 [/][: 3: unknown operand
 - Ccbins is up to date

Checking for binary updates
 [\]cat: can't open '/sbin/.magisk/modules/ccbins/tmp': No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|] - Binaries are up to date

Checking for conflicting modules
 [/]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [-]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [\]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [|]grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
grep: /sbin/.magisk/modules/ccbins/.binaries: No such file or directory
 [/] - No conflicting mods were found

But module working fine

**Comment by Zackptg5** [comment]
Definitely not supposed to be happening. Do you have acc installed? It's been interfering with the module for reasons still unknown

**Comment by Zackptg5** [comment]
Try reset ccbins option, update to latest, and see if that fixes the problem

**Comment by cadanganrendy** [comment]
Work like charm, Thanks

**Comment by Zackptg5** [comment]
Sweet, thanks!
