### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by paolosezart** [Zackptg5/Cross-Compiled-Binaries-Android#17]
Xiaomi Redmi Note 8pro phone.

![Screenshot_2020-09-27-00-54-46-653_org connectbot](https://user-images.githubusercontent.com/38177890/94349440-d296f880-005d-11eb-8aaa-b007484f8c3f.png)

![IMG_20200927_010413](https://user-images.githubusercontent.com/38177890/94349444-daef3380-005d-11eb-970c-577017f0d86c.jpg)

**Comment by Zackptg5** [comment]
Can you manually delete ccbins (/data/adb/modules/ccbins), reinstall ccbins, reboot, run ccbins - install your binaries, quit ccbins, the post the ccbins logs in /data/local/tmp? Looks like the file downloading failed

Are you running any kind of vpn or firewall mods?

**Comment by paolosezart** [comment]
I did as you asked. Here are the logs I made after the actions you described:
[ccbins-verbose-old.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5295441/ccbins-verbose-old.log)
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5295442/ccbins-verbose.log)



> 
> Are you running any kind of vpn or firewall mods?

No VPNs or firewalls are currently running.

**Comment by Zackptg5** [comment]
logs aren't showing any errors. Can you paste the output of this command:
`find /data/adb/modules/ccbins`

**Comment by paolosezart** [comment]
> logs aren't showing any errors. Can you paste the output of this command:
> `find /data/adb/modules/ccbins`

[log.txt](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5315238/log.txt)

**Comment by Zackptg5** [comment]
Can you update to the new ccbins release (just dropped it today), then try a clean install of ccbins (Choose the reset ccbins option)

**Comment by paolosezart** [comment]
I did everything as You said, now all packages work, except htop:
![IMG_20201007_155441](https://user-images.githubusercontent.com/38177890/95323230-4388ac80-08b7-11eb-87e1-7c8dbfd925b2.jpg)
![IMG_20201007_155511](https://user-images.githubusercontent.com/38177890/95323234-45eb0680-08b7-11eb-92d2-f23145ee67fa.jpg)

**Comment by Zackptg5** [comment]
Which terminal app are you using? Can you try a different terminal app such as termius? The fact that nano shows the different colors makes me think that xterm files are properly installed.
Can you run this command again? `find /data/adb/modules/ccbins`
The files we're looking for are tons of files in system/usr/share/terminfo

**Comment by paolosezart** [comment]
> Which terminal app are you using? 
 
I tried TerminalEmulator and ConnectBot.

> Can you try a different terminal app such as termius?

![Screenshot_2020-10-10-20-13-23-220_com server auditor ssh client](https://user-images.githubusercontent.com/38177890/95658684-b606c000-0b35-11eb-884f-e962d879205d.jpg)

> Can you run this command again? find /data/adb/modules/ccbins
[ccbins.txt](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5359239/ccbins.txt)

**Comment by Zackptg5** [comment]
So all the terminfo files are there, I have no idea why you're getting that error. Only thing left I could think of is contexts, try running this and hopefully it fixes it:
`chcon -R u:object_r:system_file:s0 /data/adb/modules/ccbins/system/usr/share/terminfo`

**Comment by paolosezart** [comment]
> try running this and hopefully it fixes it:
chcon -R u:object_r:system_file:s0 /data/adb/modules/ccbins/system/usr/share/terminfo

Did the same error. And in termux, htop works fine.

**Comment by Zackptg5** [comment]
Termux does everything differently. It's its own environment with its own binaries and stuff. I'd just stick with termux htop for now then since I can't replicate the error, sorry!

**Comment by paolosezart** [comment]
Okay. Perhaps the problem will be clarified in the future. Thanks anyway for trying to help. Good luck with your developments.
