### ISSUE TITLE
version's 5.05 install from magisk's repository does not see internet connection

### ISSUE THREAD

**Issue by admzzz** [Zackptg5/Cross-Compiled-Binaries-Android#18]
with or without afwall - the result is the same.
wget, curl, ping, traceroute work fine with github com. 
los 17.1, android 10

jfyi: latest two versions of bromite webview cannot be installed by the same reason, the latest installable (only when afwall is off) version is 6.0.0 (3119).

**Comment by admzzz** [comment]
_git clone_ from termux works fine.

**Comment by Zackptg5** [comment]
[ccbins_v6.0_test.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5362356/ccbins_v6.0_test.zip)
Try this test build

**Comment by admzzz** [comment]
thanks a lot, v6.0_test installed ok, but only when afwall was turned off.
can you change (or advise to change in this way, as it's not your repository) bromite webview&

**Comment by Zackptg5** [comment]
Ya, you'll need to configure afwall to not block ccbins. What issue with bromite?

**Comment by admzzz** [comment]
> you'll need to configure afwall to not block ccbins
afwall is configured to block root's traffic.
ccbins does not have it's own pid, so it can not be blocked or unblocked. 
the only way for ccbins to pass through afwall restrictions is to use pid of magisk manager (as magisk manager is allowed on afwall for sure).
v6.0_test.zip was installed only with switched off afwall, and after this switching one have to clear cache of googleservices and playmarket in order to pass safetynet check.

> What issue with bromite?
it is the same as with ccbins v5: both versions greater than 6.0.0 (3119) does not see internet connection at all regardless afwall's state.

thank you again for your work.

**Comment by Zackptg5** [comment]
I'll look into changing the pid, thanks!

**Comment by Zackptg5** [comment]
@admzzz 

What would you recommend for setting ccbins to use magisk manager's pid?
pidof -s com.topjohnwu.magisk
The problem I'm seeing is that if magisk manager is hidden, this probably won't work since it'll be replaced with a strangely named stub

**Comment by admzzz** [comment]
@Zackptg5,
you are right, i can only suggest to make bash script to be more informative for the end-user:
1) if magisk manager is unhidden, use it's pid;
2) if it is hidden, show message: "can not find magisk manager's apk, trying to connect to github's repository directly";
2.1) in case of success continue with direct connection;
2.2) in case of failure show message with choice: "for connection to github's repository script needs either disabled firewall, or permitted on the firewall root programs' access, continue or stop for preparing it?"
3) in case of "stop" script should exit and start from 1) on next run, in case of "continue" it should make 2-3 attempts to connect and show some informative message if it can not connect at all.

**Comment by Zackptg5** [comment]
Ya, I don't think it'll be practical to attempt to copy magisk manager's pid with magisk hide and the way things are heading. However, I did find that ccbins does have a unique process id assigned to it each time it runs but there's no way to force it to be the same each time which doesn't help with afwall, sorry!

**Comment by admzzz** [comment]
ok, but can you add at least the using magisk manager's pid when it is not hidden? please...

jfyi - logs of  bromite 6.1.1 installation's failure (line 122 with sh error)




[install.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5411931/install.log)
