### ISSUE TITLE
DNS Poisoning by China Mobile cell network messing with downloads from github usercontent

### ISSUE THREAD

**Issue by Zackptg5** [Zackptg5/Cross-Compiled-Binaries-Android#19]
Continued from [here](https://github.com/veez21/mod-util/issues/4)

@eebssk1

**Comment by eebssk1** [comment]
I just noticed `curl` has `--dns-*` options.
Let me mess with them first to see what it does.

**Comment by eebssk1** [comment]
Wow..`curl -I --connect-timeout 5 --dns-servers 119.29.29.29,208.67.220.220 raw.githubusercontent.com` this works for me everytime,this is the easiest one too.

**Comment by eebssk1** [comment]
This should work as long as ISP does not hijack dns request.

**Comment by eebssk1** [comment]
However this won't work when SS is on,it's interfering somehow.Should check the current network interface and force work on it.

**Comment by eebssk1** [comment]
> However this won't work when SS is on,it's interfering somehow.Should check the current network interface and force work on it.

Like
`ip route` to  get working netface except Android VPN "tun0"
then `curl -I --connect-timeout 5 --dns-interface rmnet_data1 --dns-servers 119.29.29.29,208.67.220.220 raw.githubusercontent.com`

My SIM is on slot 1 so it's rmnet1.

**Comment by eebssk1** [comment]
Oh forget to say. For your title, the dns poison currently only happen on China Mobile cellular network.

**Comment by Zackptg5** [comment]
@eebssk1 seems to a similar purpose to using doh. You got the same results with the --dns-url thing too right?

**Comment by Zackptg5** [comment]
@eebssk1 fixed :)

**Comment by eebssk1** [comment]
> 
> 
> @eebssk1 seems to a similar purpose to using doh. You got the same results with the --dns-url thing too right?

You mean `--doh-url`? There's no DNS in china  supports DoH yet so I can't test.But if it is available then this should work though.

**Comment by Zackptg5** [comment]
Ya, like this
```
--doh-url https://cloudflare-dns.com/dns-query
```
This is blocked in china though right?

**Comment by eebssk1** [comment]
> 
> 
> Ya, like this
> 
> ```
> --doh-url https://cloudflare-dns.com/dns-query
> ```
> 
> This is blocked in china though right?
> 
> What are the dns servers you used?

Good news.I just found a working DoH(DoT) server,it's provided by Aliyun which is trusted.
It's `https://223.5.5.5/dns-query`,yeah hostname is IP.It works on my end.Both tested with/without SS in cellur and WiFi.

**Comment by Zackptg5** [comment]
Alibaba has a doh server now? Think I'll add  that to ccbins as an option along with cloudflare. I'm thinking to add it as fallback in connection test or as an option user manually sets. Thoughts/ideas?

**Comment by eebssk1** [comment]
> Alibaba has a doh server now? Think I'll add that to ccbins as an option along with cloudflare. I'm thinking to add it as fallback in connection test or as an option user manually sets. Thoughts/ideas?

I'm thinking about this. You can add a volume button check to ask if users are in China(or DNS is poisoned)to decide the default action first then add a switch in ccbins menu in case users change the mind.

**Comment by eebssk1** [comment]
Or maybe you can use the fall back method during magisk module flash,this should not bother too much i think.Then add explicit notice and option in ccbins menu  to allow user choose which one.For the default you can use the test result in flash or ask user to choose on first invoke.

**Comment by Zackptg5** [comment]
I was thinking this if it doesn't take too long when testing
But if I moved everything to my website rather than using github, would this all still be necessary?

**Comment by eebssk1** [comment]
> I was thinking this if it doesn't take too long when testing
> But if I moved everything to my website rather than using github, would this all still be necessary?

If you decide to move then these will be additional and I think you'll be fine.

**Comment by Zackptg5** [comment]
Think I'm just going to add the doh stuff for now. Cloudflare didn't work on my vpn but alibaba did curiously. Doesn't matter much to me though since I have no need for doh

**Comment by Zackptg5** [comment]
@eebssk1 Pushed the doh stuff to the testing branch.

Can you try running ccbins in terminal, typing 99 as the option, switching to testing branch, and trying it out? I haven't incorporated it in the magisk module zip yet, just made the server side changes

**Comment by eebssk1** [comment]
Works nicely.

**Comment by Zackptg5** [comment]
What happaned when you flashed it? Did it auto-switch to alibaba during the install?
Just made a small improvement to the zip - if it uses alibaba for install, it'll save those settings for ccbins

**Comment by eebssk1** [comment]
> What happaned when you flashed it? Did it auto-switch to alibaba during the install?
> Just made a small improvement to the zip - if it uses alibaba for install, it'll save those settings for ccbins

The zip Always passed net check but failed to the following downloads.
I think you can just test download a blank file in raw_github_usercontent then take action when failed.I looked through the scripts, The doh fallback only happen if baidu or google  failed but not githubusercontent.

**Comment by Zackptg5** [comment]
Oh, so net check was never a problem? Reworked it by using usercontent for the install.sh download. Can you send the install log? I may end up having to do volume keys after all

**Comment by eebssk1** [comment]
Fresh flash.
“Unable to download files!"
With cellur,and with/without SS.
hmm....

**Comment by Zackptg5** [comment]
Install log?

**Comment by eebssk1** [comment]
Wrong format github.

`
- Copying zip to temp directory
- Installing 1.zip
Archive:  /data/user/0/ox.htw/cache/flash/install.zip
  inflating: module.prop
*************************
 Cross Compiled Binaries 
 by Zackptg5 
*************************
Archive:  /data/user/0/ox.htw/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/ox.htw/cache/flash/install.zip
  inflating: busybox-arm
  inflating: busybox-x86
  inflating: curl-arm
  inflating: curl-x86
  inflating: customize.sh
  inflating: module.prop
  inflating: README.md
+ true
+ getprop ro.build.version.sdk
+ API=28
+ mv -f /data/adb/modules_update/ccbins/curl-arm /data/adb/modules_update/ccbins/curl
+ set_perm /data/adb/modules_update/ccbins/curl 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/curl
+ chmod 0755 /data/adb/modules_update/ccbins/curl
+ CON=
+ '[' -z ]
+ CON=u:object_r:system_file:s0
+ chcon u:object_r:system_file:s0 /data/adb/modules_update/ccbins/curl
+ '[' -f /data/adb/modules/ccbins/doh ]
+ '[' 28 -lt 23 ]
+ alias 'curl=/data/adb/modules_update/ccbins/curl -Ls'
+ set_perm /data/adb/modules_update/ccbins/busybox-arm 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/busybox-arm
+ chmod 0755 /data/adb/modules_update/ccbins/busybox-arm
+ CON=
+ '[' -z ]
+ CON=u:object_r:system_file:s0
+ chcon u:object_r:system_file:s0 /data/adb/modules_update/ccbins/busybox-arm
+ alias 'grep=/data/adb/modules_update/ccbins/busybox-arm grep'
+ alias 'ping=/data/adb/modules_update/ccbins/busybox-arm ping'
+ test_connection
+ ui_print '- Testing internet connection'
+ true
+ echo '- Testing internet connection'
- Testing internet connection
+ /data/adb/modules_update/ccbins/curl -Ls --connect-timeout 3 -I https://www.google.com
+ /data/adb/modules_update/ccbins/busybox-arm grep -q 'HTTP/.* 200'
+ /data/adb/modules_update/ccbins/busybox-arm ping -q -c 1 -W 1 google.com
+ /data/adb/modules_update/ccbins/curl -Ls --connect-timeout 3 -I https://www.baidu.com
+ /data/adb/modules_update/ccbins/busybox-arm grep -q 'HTTP/.* 200'
+ return 0
+ '[' -f /data/adb/modules/ccbins/system/bin/ccbins ]
+ branch=testing
+ download_file /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ rm -f /data/adb/modules_update/ccbins/dlerror
+ local 'file=/data/adb/modules_update/ccbins/.checksums' 'url=https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt'
+ echo curl -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ /data/adb/modules_update/ccbins/curl -Ls -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
curl -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ '[' /data/adb/modules_update/ccbins/.checksums '==' /data/adb/modules_update/ccbins/.checksums ]
+ head -n1 /data/adb/modules_update/ccbins/.checksums
+ '['  '!=' checksums.txt ]
+ '[' -z  ]
+ return 1
+ echo -e 'Alibaba\nhttps://dns.alidns.com/dns-query'
+ tail -n1 /data/adb/modules_update/ccbins/doh
+ flag=' --doh-url https://dns.alidns.com/dns-query'
+ '[' -d /data/adb/modules/ccbins ]
+ '[' 28 -lt 23 ]
+ alias 'curl=/data/adb/modules_update/ccbins/curl -Ls --doh-url https://dns.alidns.com/dns-query'
+ download_file /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ rm -f /data/adb/modules_update/ccbins/dlerror
+ local 'file=/data/adb/modules_update/ccbins/.checksums' 'url=https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt'
+ echo curl -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ /data/adb/modules_update/ccbins/curl -Ls -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
curl -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/testing/ccbins_files/checksums.txt
+ '[' /data/adb/modules_update/ccbins/.checksums '==' /data/adb/modules_update/ccbins/.checksums ]
+ head -n1 /data/adb/modules_update/ccbins/.checksums
+ '['  '!=' checksums.txt ]
+ '[' -z ' --doh-url https://dns.alidns.com/dns-query' ]
+ abort 'Unable to download files!'
+ ui_print 'Unable to download files!'
+ true
+ echo 'Unable to download files!'
+ true
+ '[' -n /data/adb/modules_update/ccbins ]
+ rm -rf /data/adb/modules_update/ccbins
Unable to download files!
+ rm -rf /dev/tmp
+ exit 1
! Installation failed
`

**Comment by eebssk1** [comment]
The alias doesn't override?

**Comment by Zackptg5** [comment]
Apparently not. I'm going to try switching the mod to my site and post a test build here. Shouldn't need the doh stuff then

**Comment by eebssk1** [comment]
> 
> 
> Apparently not. I'm going to try switching the mod to my site and post a test build here. Shouldn't need the doh stuff then

Cloudflare haha a bit hard for CM,but should be fine with SS.

**Comment by Zackptg5** [comment]
Oh duh, I need to redefine the function after updating the alias. I tried moving everything to my website and it works fine but is still a little janky so I'll try to make the github doh solution work first. Here's a new test build, think I got the kinks all worked out
[ccbins_v7.0-test.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5398367/ccbins_v7.0-test.zip)

**Comment by eebssk1** [comment]
> Oh duh, I need to redefine the function after updating the alias. I tried moving everything to my website and it works fine but is still a little janky so I'll try to make the github doh solution work first. Here's a new test build, think I got the kinks all worked out
> [ccbins_v7.0-test.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5398367/ccbins_v7.0-test.zip)
> 
> I have reworked installer quite a bit this time. If checksums file download fails, it'll use alibaba doh
> 
> I have noticed that alibaba doh is significantly slower than cloudflare for me, not sure if it'll be the same for you. Using cloudflare doesn't work right?

Fresh install ran smoothly,succeed using DoH.And ccbins first time invoke also OK.

The last question u ask is about how dns working nowadays.Since you are using CN DNS,it returns the nearst server ip for you and choose the CN one if possible.Github only has one worldwide ip so it's always slow for me,and  net to CN DNS is slow for you,Which you may know what we feel.The situation is similar for me to use CF.

**Comment by Zackptg5** [comment]
> 
> 
> > Oh duh, I need to redefine the function after updating the alias. I tried moving everything to my website and it works fine but is still a little janky so I'll try to make the github doh solution work first. Here's a new test build, think I got the kinks all worked out
> > [ccbins_v7.0-test.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5398367/ccbins_v7.0-test.zip)
> > I have reworked installer quite a bit this time. If checksums file download fails, it'll use alibaba doh
> > I have noticed that alibaba doh is significantly slower than cloudflare for me, not sure if it'll be the same for you. Using cloudflare doesn't work right?
> 
> Fresh install ran smoothly,succeed using DoH.And ccbins first time invoke also OK.
> 
> The last question u ask is about how dns working nowadays.Since you are using CN DNS,it returns the nearst server ip for you and choose the CN one if possible.Github only has one worldwide ip so it's always slow for me,and net to CN DNS is slow for you,Which you may know what we feel.The situation is similar for me to use CF.
Not sure what you're asking here. I have the installer use no doh server by default, then fall back to alibaba if there's issues. In ccbins itself, you can choose if you want to change it to nothing, alibaba, or cloudflare so the speed thing shouldn't be an issue since only CN users with issues would likely use alibaba

**Comment by eebssk1** [comment]
> > > Oh duh, I need to redefine the function after updating the alias. I tried moving everything to my website and it works fine but is still a little janky so I'll try to make the github doh solution work first. Here's a new test build, think I got the kinks all worked out
> > > [ccbins_v7.0-test.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5398367/ccbins_v7.0-test.zip)
> > > I have reworked installer quite a bit this time. If checksums file download fails, it'll use alibaba doh
> > > I have noticed that alibaba doh is significantly slower than cloudflare for me, not sure if it'll be the same for you. Using cloudflare doesn't work right?
> > 
> > 
> > Fresh install ran smoothly,succeed using DoH.And ccbins first time invoke also OK.
> > The last question u ask is about how dns working nowadays.Since you are using CN DNS,it returns the nearst server ip for you and choose the CN one if possible.Github only has one worldwide ip so it's always slow for me,and net to CN DNS is slow for you,Which you may know what we feel.The situation is similar for me to use CF.
> 
> Not sure what you're asking here. I have the installer use no doh server by default, then fall back to alibaba if there's issues. In ccbins itself, you can choose if you want to change it to nothing, alibaba, or cloudflare so the speed thing shouldn't be an issue since only CN users with issues would likely use alibaba

I'm just answering `I have noticed that alibaba doh is significantly slower than cloudflare for me, not sure if it'll be the same for you. Using cloudflare doesn't work right?`
Sorry if you get confused because of my bad grammar.

The installer works fine now though sometimes it timeout download files even with SS.Maybe just because the ocean cable is overloaded.Well neverdmind.

**Comment by Zackptg5** [comment]
Oh ok, gotcha. I'll drop the next update after I look over it some more

**Comment by Zackptg5** [comment]
Pushed update :)
