### ISSUE TITLE
coreutils rm issues

### ISSUE THREAD

**Issue by cxyzzz** [Zackptg5/Cross-Compiled-Binaries-Android#2]
run `coreutils --coreutils-prog=rm .wget-hsts`
show rm '.wget-hsts' rm: cannot remove '.wget-hsts': Invalid argument, but use `-f` is ok

**Comment by Zackptg5** [comment]
Confirmed. Not sure why this is happening but I'll look into it. Using -f flag didn't fix it in my case

**Comment by Zackptg5** [comment]
Welp, think I found it. No problems if run as root. Are you on Q by chance? There's been an issue with many different binaries being restricted in Q

**Comment by cxyzzz** [comment]
@Zackptg5  I use Android P.

Yes, ping for busybox must have root privileges.run coreutils rm as root is ok.
