### ISSUE TITLE
tmux and screen term

### ISSUE THREAD

**Issue by FerryAr** [Zackptg5/Cross-Compiled-Binaries-Android#20]
would love it can be installed in my phone without full chroot or termux.

**Comment by Zackptg5** [comment]
Not sure what you're taking about here. You can use these binaries in any terminal app
You mean use them without root (ie magisk)? That's on google for locking us out of the OS

**Comment by FerryAr** [comment]
i requested tmux and screen to be cross compiled.
are that possible?

**Comment by Zackptg5** [comment]
Ooooohhhhhh. I'll give them a look over and get back to you :)

**Comment by Zackptg5** [comment]
I'm unable to get either of them to compile properly. libevent is giving me issues (dependency for tmux) and screen is giving issues as well

**Comment by Zackptg5** [comment]
Got an update. I got tmux to compile but it segfaults immediately. I'm not really sure what the problem is with it

**Comment by Zackptg5** [comment]
Ok, so screen is definitely not going to happen. It relies on functions obsolete or explicitly disallowed by SELinux (such as crypt). Not sure about tmux, I'll post it here if you want to try it, I may just not be using a supported app or something, not really sure how it works
[tmux-arm64.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/6055152/tmux-arm64.zip)

Does this work for you?

**Comment by Zackptg5** [comment]
Looks like it won't work out :(
