### ISSUE TITLE
Aria2 don't check certificates

### ISSUE THREAD

**Issue by unixandria-xda** [Zackptg5/Cross-Compiled-Binaries-Android#29]
Aria2 cannot find the ca-certificates bundle because it doesn't exist on android. 

You need to compile the option out, there is no cli flag to disable certificate loading

**Comment by Zackptg5** [comment]
It won't work at all with ssl without it. The cert is created by ccbins from the existing files on the device and there's a script in [my build repo](https://github.com/Zackptg5/Aria2-Android) that does the same thing.

See the install script here: https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/blob/master/aria2/install.sh
