### ISSUE TITLE
zstd request

### ISSUE THREAD

**Issue by KaMyKaSii** [Zackptg5/Cross-Compiled-Binaries-Android#3]
Could you consider providing a static build of the [zstd](https://github.com/facebook/zstd) compressor? I can use it through Termux but it would be great to have a single binary that also works in TWRP without having to point a library path. Thank you very much for your time and great work!

**Comment by Zackptg5** [comment]
Sure thing! I'll let you know once its done

**Comment by Zackptg5** [comment]
I'll be adding it to this build script too if you want to build it yourself down the road or whatever: https://github.com/Zackptg5/Misc-Binaries-For-Android-Build-Script

**Comment by Zackptg5** [comment]
zstd is added to testing branch. I'm working on some stuff with zsh and once that's done, I'll push it to master

**Comment by Zackptg5** [comment]
zstd has been added to master branch

**Comment by KaMyKaSii** [comment]
> zstd has been added to master branch

Thank you very much friend!
