### ISSUE TITLE
System mode support (without Magisk)?

### ISSUE THREAD

**Issue by AnonVendetta** [Zackptg5/Cross-Compiled-Binaries-Android#30]
This isn't an issue, more of a request.

I would like to see system mode support (direct installation into system partition), without needing to install ccbins via Magisk. Many of these binaries are immensely useful, I'd like to make them a permanent part of my ROMs.

I see no big obstacles here. As long as the device is rooted, then it's a trivial matter to remount the system partition as writable. Any root method would work, not just Magisk. I personally still prefer SuperSU myself, and i continue to run it on several older devices. But I'm a longtime old school Android user. If there were an issue like the binary already existing, it could just be renamed or backed up to a location like internal storage/MicroSD.

I like that Magisk has tons of useful modules. But I resent that many mod creators are limiting their mods to being installable via Magisk only, when many of these would otherwise work fine without it. The good old days of direct system mode installation are nearly gone.

Thanks!

**Comment by Zackptg5** [comment]
The primary reason I dropped support for non-magisk root solutions is that I no longer own any devices where supersu or any root solution other than magisk is viable. I sold off my old devices some time ago. I can't/won't support something that I can't test myself.
All of the binaries here can just be copy pasted to the system partition, all you'd need to do is set perms afterwards and for the few that have some symlink shenanigans or whatever, the install.sh script in it's folder can be easily modified to automate that process (such as coreutils).
