### ISSUE TITLE
A build script for 'iw' ARM/ARM64 (Android)

### ISSUE THREAD

**Issue by kimocoder** [Zackptg5/Cross-Compiled-Binaries-Android#31]
Feel free to use it, extend or so in order to keeping
tools on the edge 👍 

https://github.com/kimocoder/android_tools_iw

**Comment by Zackptg5** [comment]
Awesome, thanks!

**Comment by Zackptg5** [comment]
Hey, in the process of compiling iw with your script and I was able to get static compiles by replacing the -fPIE and -pie flags with -static in CFLAGS and LDFLAGS in build_env in case you're interested (I always shoot for static compiles if possible)

**Comment by Zackptg5** [comment]
@kimocoder Looking into adding libnl and iw to my main build script with latest ndk and found that you can remove the disable-cli flag if using API of 26 or newer, getsubopt was added to ndk at that point
