### ISSUE TITLE
What about strace binary?

### ISSUE THREAD

**Issue by min050820** [Zackptg5/Cross-Compiled-Binaries-Android#32]
Yes. I know strace won't be super useful.

But it doesn't hurt to have one, right?

I've already seen somebody distributing strace in magisk module, so it doesn't seem to be too hard.

**Comment by Zackptg5** [comment]
It's already here lol - in the [strace folder](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/tree/master/strace)
v5.5 and older were simple plug and play for compiling but starting with v5.6, I needed some hackery to get mpers32 working with 64it builds.

**Comment by min050820** [comment]
Opps, now I need to debug why my terminal replied "Inaccesible or not found".

Sorry if I bothered you.
