### ISSUE TITLE
htop does not work

### ISSUE THREAD

**Issue by halis300** [Zackptg5/Cross-Compiled-Binaries-Android#33]
htop does not work in termux and in TerminalEmulator
![Screenshot_20210228-161943_1](https://user-images.githubusercontent.com/79767757/109424026-43ae5380-79e2-11eb-9e70-22462ddb0116.png)
![Screenshot_20210228-162559_1](https://user-images.githubusercontent.com/79767757/109424028-4446ea00-79e2-11eb-9053-8d1a086d4d28.png)

The command export changes the error messagein termux. htop works if I open it without root in termux (installed within termux 'apt install htop'):
![Screenshot_20210228-163359_1](https://user-images.githubusercontent.com/79767757/109424174-dfd85a80-79e2-11eb-9ac8-4e087350022c.png)
(however htop without root is useless. Big thx here to google)

Another issue, that might be related is, that htop does not appear in '/system/bin/'. But I could find it in '/data/adb/modules/ccbins/system/bin'. It looks like normal installed in ccbins:
![Screenshot_20210228-183209_1](https://user-images.githubusercontent.com/79767757/109427599-5ed58f00-79f3-11eb-9813-7279f383a0df.png)

However, it is not:
![Screenshot_20210228-183504_1](https://user-images.githubusercontent.com/79767757/109427698-dd323100-79f3-11eb-8232-09713ea6cb53.png)

Strange thing is, that $path is empty:
![Screenshot_20210228-183751_1](https://user-images.githubusercontent.com/79767757/109427770-313d1580-79f4-11eb-874b-fbb460d2a35d.png)

related issue (however, I could find a workaroud):
https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/issues/17

**Comment by Zackptg5** [comment]
So this is a termux problem. Run `echo $PATH` and you'll see the problem: termux uses its own environment. See termux vs termius (standard terminal):
![Screenshot_20210308-071408](https://user-images.githubusercontent.com/5107713/110320332-1e22da80-7fde-11eb-9d0e-552fae007cf2.png)
![Uploading Screenshot_20210308-071613.png…]()

**Comment by Zackptg5** [comment]
![Screenshot_20210308-071613](https://user-images.githubusercontent.com/5107713/110320697-b4570080-7fde-11eb-9bbb-3cbdf7a0bb92.png)

**Comment by halis300** [comment]
By the way, now it works in both, "TerminalEmulator" and "Termux". I did not change anything except updating
