### ISSUE TITLE
request: nmap and list of newer binaries

### ISSUE THREAD

**Issue by Seplx** [Zackptg5/Cross-Compiled-Binaries-Android#34]
Since tcpdump is included it might be useful to add something to link the given ip addresses to a specific device.

Also some of the binaries here have newer versions
Nano (5.6.1)
Cpio 2.13 (Android Image Kitchen has some issues with 2.13 recommending you to stick to 2.12 for a stable android bootimage repack, not sure if this hurts somebody in any way)
Iw (5.9.3)
Openssl (v1.1.1j)
Sqlite3 (3.35.0)
Strace (5.11)
Tar (1.34)
Vim (v8.2.2604)
Xmlstarlet, there is a fork that is getting updated [here](https://github.com/dimitern/xmlstarlet) however I'm not at all sure about this
Zstd (v1.4.9)

**Comment by Zackptg5** [comment]
So cpio 2.13 is pretty broken and so I've been sticking with 2.12 based on @osm0sis recommendation (he knows way more about cpio than me, I hardly use it lol). I'll work on updating the others, thanks! See what I can do about nmap

**Comment by Zackptg5** [comment]
Not sure where all the distros are getting iw v5.9.3 from. Latest on the kernel repo is still 5.9: https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git

**Comment by Zackptg5** [comment]
I'll stick with current xmlstarlet. Doesn't look like much has changed featureset-wise.

Lots of changes from strace 5.10 -> 5.11 which not surprisingly broke things again so we may be stuck with 5.10 for the time being

**Comment by Zackptg5** [comment]
Updated all binaries listed except cpio. Will look into nmap tomorrow

**Comment by Zackptg5** [comment]
[nmap-arm.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/6138722/nmap-arm.zip)
Got a test build for you. Arm64 is giving me issues - won't compile statically for some reason (I'll get it eventually)

**Comment by Seplx** [comment]
> [arm64.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/6138919/arm64.zip)
> @Seplx
> Got a test build for you. Arm64 is giving me issues - won't compile statically for some reason so I'm going dynamic only difference is that for dynamic builds, you need to be on android 5.0 or newer

Didn't test nping and ncat since I don't really know how use them. They do execute tho.
nmap appears to work,  however it cannot find some things. Tested on poco m3 android 10

```
citrus:/ # nmap -sn 192.168.1.0/24
Starting Nmap 7.91 ( https://nmap.org ) at 2021-03-15 09:45 CET
Cannot find nmap-payloads. UDP payloads are disabled.
mass_dns: warning: Unable to open /etc/resolv.conf. Try using --system-dns or specify valid servers with --dns-servers
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
Nmap scan report for 192.168.1.1
Cannot find nmap-mac-prefixes: Ethernet vendor correlation will not be performed
Host is up (0.021s latency).
MAC Address: ############### (Unknown)
Nmap scan report for 192.168.1.31
Host is up (0.13s latency).
MAC Address: ############### (Unknown)
Nmap scan report for 192.168.1.35
Host is up (0.0088s latency).
MAC Address: ############### (Unknown)
Nmap scan report for 192.168.1.51
Host is up (0.042s latency).
MAC Address: ############### (Unknown)
Nmap scan report for 192.168.1.34
Host is up.
Nmap done: 256 IP addresses (5 hosts up) scanned in 2.40 seconds
citrus:/ # nmap 192.168.1.0/24                                                                                                                                                                                                                                                                                              
Starting Nmap 7.91 ( https://nmap.org ) at 2021-03-15 09:45 CET
Unable to find nmap-services!  Resorting to /etc/services
Unable to open /etc/services for reading service inform
```ation
QUITTING!

**Comment by Zackptg5** [comment]
Hmm so some of that stuff isn't present in android. I'll look into it and see what I can come up with

**Comment by Zackptg5** [comment]
Got it figured out. There's some other files in usr/share that I didn't include. Best way to do this is to just install it through ccbins and test it out:
```
su -c ccbins
99
2
2
```
Then install nmap (it's dynamic linked binary so choose option 7). Reboot, and give it a whirl :)

**Comment by Zackptg5** [comment]
Added nmap to master branch
