### ISSUE TITLE
Dowloading Error

### ISSUE THREAD

**Issue by nibirrayy** [Zackptg5/Cross-Compiled-Binaries-Android#37]
I am getting download error like this
![Screenshot_20210803-214414_Termux](https://user-images.githubusercontent.com/12048453/128050252-6b387880-e768-4be9-aa67-aa9b2e7d4454.png)

 I just downloaded the zip and installed the using magisk. Did i miss anything

**Comment by Zackptg5** [comment]
Pushed fix, sorry!
