### ISSUE TITLE
Can't install curl

### ISSUE THREAD

**Issue by bengalih** [Zackptg5/Cross-Compiled-Binaries-Android#38]
Just installed latest ccbins on Pixel 3 XL 11.

Cant install curl (for acc).

Error:

```
Downloading Curl
 [|]Download error for /dev/0NE6/.magisk/modules/ccbins/install.sh!
 [/] - Curl has been installed!

Reboot for changes to take effect
```

Tcpdump and zip installed no problem.

**Comment by Zackptg5** [comment]
You try removing and reinstalling curl? Sounds like github had a brainfart or you had a network connection issue for a hot second there. 
That file hasn't been changed in a long time so no md5sum issues with it

**Comment by bengalih** [comment]
It didn't show it was installed.  I tried several times including reboots.
When it didn't work I tried tcpdump and zip and both installed no problem,
then tried curl again and it failed.
I was playing around with it yesterday and somehow got acc to use it by
copying the curl binary to another directory manually.

so it is working for its purpose now, but ccbins shows it is uninstalled
and I get the error message each time I try to install it.

Can I get you some other type of log to see what's up?

**Comment by Zackptg5** [comment]
It may think it's fully installed then. Delete the curl line in /data/adb/modules/ccbins/.installed, then run ccbins again.

Log is: /data/local/tmp/ccbins.log

**Comment by bengalih** [comment]
There is no curl entry in .installed.
To be clear, curl is apparently installed with ccbins into the ./modules/ccbins/ directory, as (I assume) ccbins uses it to download all of its files.  But it is not installed into system/bin when I attempt to install it with the aforementioned error.

All the other binaries seem to install fine into system and are accessible anywhere via the path, but curl will not install.

I can get it to run if I am in the directory it exists, manually copy or try to modify the path, but this isn't how the other utilities work nor how I used it in the past.  I've been away from ACC for a while, which was my main reason for finding ccbins, but I'm pretty sure it used to pack wget not curl (?).  Anyway I had that working on my phone on A10, I am on A11 now.

Let me know what else you need.
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/7003635/ccbins-verbose.log)

**Comment by bengalih** [comment]
So I want to add something here...maybe I was doing something wrong?  I see there is an option to install curl via option 6 (what I was doing) and option 7 (dynamic linked).  I just tried to install with option 7 and it seems to work. 
It shows in the .installed file as dynamic.

I don't really know in the context of ccbins the difference between the two is, and it seems I have my needed functionality for now, but if I should be able to install it as a static from option 6, then that doesn't work for me.

**Comment by Zackptg5** [comment]
Ok, log showed the problem. Looked like windows git screwed me over again with EOL changes. Pushed fix, thanks!

BTW, use dynamic linked if available for normal device usage - has more features. Use static linked if you're using it in an installer zip
