### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by lukemin** [Zackptg5/Cross-Compiled-Binaries-Android#39]
- Copying zip to temp directory
- Installing Cross_Compiled_Binaries-v7.2(9).zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/bpc.c/cache/flash/install.zip
  inflating: module.prop
*************************
 Cross Compiled Binaries 
 by Zackptg5 
*************************
*******************
Archive:  /data/user/0/bpc.c/cache/flash/install.zip
  inflating: customize.sh
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/bpc.c/cache/flash/install.zip
  inflating: functions.sh
  inflating: .gitattributes
  inflating: .gitignore
  inflating: README.md
  inflating: busybox-arm
  inflating: busybox-x86
  inflating: curl-arm
  inflating: curl-x86
  inflating: customize.sh
  inflating: module.prop
  inflating: wg-arm
  inflating: wg-quick-arm
  inflating: wg-quick-x86
  inflating: wg-x86
+ true
+ set_perm /data/adb/modules_update/ccbins/busybox- 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/busybox-
chown: /data/adb/modules_update/ccbins/busybox-: No such file or directory
+ return 1
+ alias 'awk=/data/adb/modules_update/ccbins/busybox- awk'
+ alias 'grep=/data/adb/modules_update/ccbins/busybox- grep'
+ alias 'md5sum=/data/adb/modules_update/ccbins/busybox- md5sum'
+ alias 'ping=/data/adb/modules_update/ccbins/busybox- ping'
+ mv -f /data/adb/modules_update/ccbins/curl- /data/adb/modules_update/ccbins/curl
mv: can't rename '/data/adb/modules_update/ccbins/curl-': No such file or directory
+ set_perm /data/adb/modules_update/ccbins/curl 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/curl
chown: /data/adb/modules_update/ccbins/curl: No such file or directory
+ return 1
+ mv -f /data/adb/modules_update/ccbins/wg- /data/adb/modules_update/ccbins/wg
mv: can't rename '/data/adb/modules_update/ccbins/wg-': No such file or directory
+ set_perm /data/adb/modules_update/ccbins/wg 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/wg
chown: /data/adb/modules_update/ccbins/wg: No such file or directory
+ return 1
+ mv -f /data/adb/modules_update/ccbins/wg-quick- /data/adb/modules_update/ccbins/wg-quick
mv: can't rename '/data/adb/modules_update/ccbins/wg-quick-': No such file or directory
+ set_perm /data/adb/modules_update/ccbins/wg-quick 0 0 0755
+ chown 0:0 /data/adb/modules_update/ccbins/wg-quick
chown: /data/adb/modules_update/ccbins/wg-quick: No such file or directory
+ return 1
+ '[' -f /data/adb/modules/ccbins/doh ]
+ alias 'wg=/data/adb/modules_update/ccbins/wg'
+ alias 'wg-quick=/data/adb/modules_update/ccbins/wg-quick'
+ '[' -f /data/adb/modules_update/ccbins/doh ]
+ '[' 30 -lt 23 ]
+ alias 'curl=/data/adb/modules_update/ccbins/curl -Ls'
+ pm list packages com.wireguard.android
+ '['  ]
+ . /data/adb/modules_update/ccbins/functions.sh
+ test_connection
+ ui_print '- Testing internet connection'
+ true
+ echo '- Testing internet connection'
- Testing internet connection
+ /data/adb/modules_update/ccbins/curl -Ls --connect-timeout 3 -I https://www.google.com
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 4: /data/adb/modules_update/ccbins/curl: not found
+ /data/adb/modules_update/ccbins/busybox- grep -q 'HTTP/.* 200'
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 4: /data/adb/modules_update/ccbins/busybox-: not found
+ /data/adb/modules_update/ccbins/busybox- ping -q -c 1 -W 1 google.com
+ /data/adb/modules_update/ccbins/busybox- grep -q 'HTTP/.* 200'
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 4: /data/adb/modules_update/ccbins/busybox-: not found
+ /data/adb/modules_update/ccbins/curl -Ls --connect-timeout 3 -I https://www.baidu.com
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 4: /data/adb/modules_update/ccbins/curl: not found
+ /data/adb/modules_update/ccbins/busybox- ping -q -c 1 -W 1 baidu.com
+ return 0
+ '[' -f /data/adb/modules/ccbins/system/bin/ccbins ]
+ branch=master
+ download_file /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt
+ rm -f /data/adb/modules_update/ccbins/dlerror
+ local 'file=/data/adb/modules_update/ccbins/.checksums' 'url=https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt'
+ rm -f /data/adb/modules_update/ccbins/.checksums
+ /data/adb/modules_update/ccbins/curl -Ls -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 15: /data/adb/modules_update/ccbins/curl: not found
+ '[' /data/adb/modules_update/ccbins/.checksums '==' /data/adb/modules_update/ccbins/.checksums ]
+ head -n1 /data/adb/modules_update/ccbins/.checksums
+ '['  '==' checksums.txt ]
+ return 1
+ '[' -z  ]
+ echo -e 'Alibaba\nhttps://dns.alidns.com/dns-query'
+ tail -n1 /data/adb/modules_update/ccbins/doh
+ flag=' --doh-url https://dns.alidns.com/dns-query'
+ '[' -d /data/adb/modules/ccbins ]
+ . /data/adb/modules_update/ccbins/functions.sh
+ download_file /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt
+ rm -f /data/adb/modules_update/ccbins/dlerror
+ local 'file=/data/adb/modules_update/ccbins/.checksums' 'url=https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt'
+ rm -f /data/adb/modules_update/ccbins/.checksums
+ /data/adb/modules_update/ccbins/curl -Ls -o /data/adb/modules_update/ccbins/.checksums https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/ccbins_files/checksums.txt
/data/user/0/bpc.c/cache/flash/update-binary: /data/adb/modules_update/ccbins/customize.sh: line 15: /data/adb/modules_update/ccbins/curl: not found
+ '[' /data/adb/modules_update/ccbins/.checksums '==' /data/adb/modules_update/ccbins/.checksums ]
+ head -n1 /data/adb/modules_update/ccbins/.checksums
+ '['  '==' checksums.txt ]
+ return 1
+ abort 'Unable to download files!'
+ ui_print 'Unable to download files!'
+ true
+ echo 'Unable to download files!'
+ true
+ '[' '!' -z /data/adb/modules_update/ccbins ]
+ rm -rf /data/adb/modules_update/ccbins
Unable to download files!
+ rm -rf /dev/tmp
+ exit 1
! Installation failed

**Comment by Zackptg5** [comment]
Ok, looks like the ARCH32 variable was removed in the magisk alpha build. I don't support those since they're subject to frequent change so I'd recommend going back to main release magisk build for now. I'll keep this open as a reminder to myself in the event this change makes it to main release

**Comment by Zackptg5** [comment]
Commit of interest: https://github.com/topjohnwu/Magisk/commit/5e1fba3603100b87413852f60e9615d6c316c4ab

**Comment by Zackptg5** [comment]
Seems that there's a lot more ppl using magisk alpha builds than I had anticipated. Fix was simple enough so should be good to go now :)
