### ISSUE TITLE
nethogs, iftop, wavemon for network debugging

### ISSUE THREAD

**Issue by eMPee584** [Zackptg5/Cross-Compiled-Binaries-Android#4]
Some of my favorite tools for figuring out networking issues, would love to have them avail without a full chroot.. each of them is plain C and less than 100KiB..

**Comment by Zackptg5** [comment]
I'll give them a look, I think I tried compiling a different network tool and called it quits cause I couldn't get libpcap to cross compile. Either way, I'll let you know what comes up from it

**Comment by Zackptg5** [comment]
Sorry man but I can't get libpcap to cross compile which kills the first 2, wavemon won't cross compile at all, looks like they have no support for android yet

**Comment by eMPee584** [comment]
Perfectly fine, difficult thangs... Thanks a lot for having a go!

**Comment by Bodya-Kolibass** [comment]
> I can't get libpcap to cross compile

I hope that my little script for compiling tcpdump will help you understand how to build libpcap.

```#!/bin/bash

# How to compile static binary tcpdump for android (abi)aarch64.

export NDK=/path/to/android-ndk # location NDK
export PCAPV=1.9.1 # version libpcap sources
export TCPDV=4.9.3 # version tcpdump sources
export KERNV=5 # major number of your release Kernel version from the command "uname -a"
mkdir build
cd build
wget https://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
tar xzf libpcap-$PCAPV.tar.gz
cd libpcap-$PCAPV
export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
export API=26
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export LD=$TOOLCHAIN/bin/$TARGET-ld
export CFLAGS='-Os'
./configure --host $TARGET --with-pcap=linux
make
export LIBPCAP_PATH=$(pwd)
cd ..
wget https://www.tcpdump.org/release/tcpdump-$TCPDV.tar.gz
tar xzf tcpdump-$TCPDV.tar.gz
cd tcpdump-$TCPDV
export ac_cs_linux_vers=$KERNV
export CFLAGS="-static -I${LIBPCAP_PATH} -L${LIBPCAP_PATH}"
export CPPFLAGS=-static
export LDFLAGS=-static
export STRIP=$TOOLCHAIN/bin/$TARGET-strip
./configure --host $TARGET
make
$STRIP tcpdump
cp tcpdump ../../tcpdump
cd ../..
#rm -rf build

**Comment by Zackptg5** [comment]
@Bodya-Kolibass

Thanks, I'll look into it. What ndk did you use?

**Comment by Bodya-Kolibass** [comment]
> What ndk did you use?

Latest stable version.

**Comment by Zackptg5** [comment]
Ok, trying this all out again and same as before - libpcap compiles fine dynamic linked, but not static. Either way, since I have dynamic linked support now I may be able to add dynamically linked binaries

**Comment by Zackptg5** [comment]
> > What ndk did you use?
> 
> Latest stable version.

So interesting behavior. If I use the resulting directory from `make install` for libpcap's include/lib locations, compilation of any binaries relying on it will fail. If I just use the original directory, it'll work. Got tcpdump ready to go.

Nethogs has no configure script of any kind and it seems to be ignoring any C/LDFLAGS I send to it's make command
Iftop keeps complaining about my cross-compiled ncurses not containing mvchgat - I have no idea how to enable that (tried --enable-mvchgat=yes)

**Comment by Zackptg5** [comment]
@eMPee584 
Figured out libpcap incidentally so revisiting this issues. Think I actually got iftop so those will hopefully be added to the repo this coming week :)
Hopefully I can get as lucky with the others

**Comment by Zackptg5** [comment]
If top and nethogs have both been added to repo

**Comment by eMPee584** [comment]
awesome, thanks : )

**Comment by Zackptg5** [comment]
Been working off/on to fet wavemon but I don't have high hopes for it. If i get it, it'll show up in the repo

**Comment by Zackptg5** [comment]
Leaving open till I get/give up on wavemon. Getting close I think

**Comment by Zackptg5** [comment]
@eMPee584 
Finally got it to compile properly but it says "no supported wireless interfaces found! Check manpage for help." Even when specifying the proper interface. I'm not familiar with wavemon so any input would be appreciated :)

[wavemon-arm64.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5934822/wavemon-arm64.zip)

**Comment by Zackptg5** [comment]
Tested it out with a kernel dev and looks like it won't work with most android devices. The kernel needs to support wireless extensions which most don't. Tried it on a quick test build that did and it mostly worked in that the binary is compiled correctly. I'll leave it up for any fringe cases in which an android device can actually use it :)
