### ISSUE TITLE
Possible to add ZeroTierOne?

### ISSUE THREAD

**Issue by glblduh** [Zackptg5/Cross-Compiled-Binaries-Android#42]
It is possible to add ZeroTierOne? Because the Android app doesn't support layer 2 because of the lack of tap module access from Android.

[The github repo](https://github.com/zerotier/ZeroTierOne)

**Comment by Zackptg5** [comment]
This repo is only for binaries, not entire programs. You talking about some specific binary that it's looking for (I'm not too familiar with zerotierone)

**Comment by glblduh** [comment]
Okay thanks
