### ISSUE TITLE
[BUG] gawk-arm getline prints empty

### ISSUE THREAD

**Issue by SedapnyaTidur** [Zackptg5/Cross-Compiled-Binaries-Android#49]
There is a bug with the gawk-arm. Here is the example:
```bash
$ ./gawk-arm 'BEGIN { cmd="echo hello"; cmd | getline; print $0; close(cmd) }'

$ gawk 'BEGIN { cmd="echo hello"; cmd | getline; print $0; close(cmd) }'
hello
$ busybox awk 'BEGIN { cmd="echo hello"; cmd | getline; print $0; close(cmd) }'
hello
$
$ ./gawk-arm --version | head -n1
GNU Awk 5.1.0, API: 3.0
$ gawk --version | head -n1
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
$ busybox awk 2>&1 | head -n1
BusyBox v1.31.1 (2019-12-04 03:47:16 UTC) multi-call binary.
```

**Comment by Zackptg5** [comment]
I'm unable to replicate the issue, works fine on my end. Does the binary have proper perms and chcon set (since it's outside of normal ccbins placement)?

**Comment by SedapnyaTidur** [comment]
The issue actually is not about all those things but a lack of patchings. There is the output of `strace`.
```bash
$ strace -f ./gawk-arm 'BEGIN { cmd="echo a"; cmd|getline; print }' 2>&1 | grep 'sh'
...
[pid 27102] execve("/bin/sh", ["sh", "-c", "echo a"], 0xffe1a090 /* 22 vars */ <unfinished ...>
....
```

As you can see, it is looking for `/bin/sh` which is not a valid path for any androids. And here's the output gawk in termux.
```bash
$ strace -f gawk 'BEGIN { cmd="echo a"; cmd|getline; print }' 2>&1 | grep 'sh'
...
[pid 27420] execve("/data/data/com.termux/files/usr/bin/sh", ["sh", "-c", "echo a"], 0xfff41ee0 /* 22 vars */ <unfinished ...>
...
```

**Comment by Zackptg5** [comment]
Can you try this bin? Should fixed path on 
[gawk.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/7598226/gawk.zip)
it

**Comment by SedapnyaTidur** [comment]
Yes, it fixed the problem. Well done.

**Comment by Zackptg5** [comment]
Awesome, I'll update the binaries and build script here in the next half hour or so (also pushing rclone). You'll have to remove/reinstall gawk if using ccbins since version number is the same (5.1.1)

**Comment by SedapnyaTidur** [comment]
@Zackptg5 Don't worry about that. Actually I'm using these binaries in Jackpal Terminal with a busybox for a coming soon project. It would be great if you could build that one too (busybox). Also a `file` command is very appreciated. And just now, I noticed that `bash` has a bug with **horizontal-scroll-mode**. When you're typing a very long text, it does not wrap to the next line. Even though I've set `set horizontal-scroll-mode off` in .inputrc has no effect. But that's a different issue, I guess.

**Comment by Zackptg5** [comment]
Already pushed them lol

I'll look into the bash issue.
I don't build busybox because osm0sis has the covered way better then I ever could
[Builds here](https://github.com/Magisk-Modules-Repo/busybox-ndk)
[Build script here](https://github.com/osm0sis/android-busybox-ndk)

**Comment by Zackptg5** [comment]
> @Zackptg5 Don't worry about that. Actually I'm using these binaries in Jackpal Terminal with a busybox for a coming soon project. It would be great if you could build that one too (busybox). Also a `file` command is very appreciated. And just now, I noticed that `bash` has a bug with **horizontal-scroll-mode**. When you're typing a very long text, it does not wrap to the next line. Even though I'd set `set horizontal-scroll-mode off` in .inputrc has no effect. But that's a different issue, I guess.

Maybe it could be related to one of the supporting files such as /system/etc/bash.bashrc or the /sdcard/.bashrc file.
Maybe try commenting out the `shopt -s checkwinsize` line in bash.bashrc?

In the process of updating bash now and looks like inputrc wasn't patched so I'll fix that so rather than nonexistent ~/.inputrc, it'll be /sdcard/.inputrc. /system/etc/inputrc was already patched so guess I missed the user one

**Comment by SedapnyaTidur** [comment]
Hurray another fixes. The first one worked like a charm with/without `.bashrc` but **not** the second one with/without `.bashrc`.

**Comment by Zackptg5** [comment]
That's strange, the fix is present in both. What are the exact steps you use to cause the problem so I can do some more testing?

**Comment by SedapnyaTidur** [comment]
There is no special steps here. I just rename the `.bashrc` to `bashrc`, then run exec the binary and start typing. Later, I'd `source` the bashrc and start another typing. I even unset `$TERM` and `$TERMINFO` but that makes things worse for both of them. They require these variables somehow.

**Comment by Zackptg5** [comment]
Hmm so I tried the second binary and it worked fine for me, can you try in ccbins typing in `99` at option menu and switching to testing branch and installing bash from there?

**Comment by SedapnyaTidur** [comment]
Just did. They worked fine. So thanks again for your hard work. Don't bother too much with it - enjoy your life.

**Comment by Zackptg5** [comment]
Sweet, thanks man! I plan on tweaking ccbins with wireguard and then I'll push to stable
