### ISSUE TITLE
Work With Selinux Enforcing??

### ISSUE THREAD

**Issue by Ayush-Singh2310** [Zackptg5/Cross-Compiled-Binaries-Android#50]
Ccbins magisk module doesn't install with _Selinux_ _Enforcing_.
Same for download with ccbins binary in terminal app.

Any way I can make it work with **Enforcing**??

**Comment by Zackptg5** [comment]
It works fine with enforcing, selinux is not related to most of the binaries here. Any problems you're having is due to something else such another magisk module or your rom
