### ISSUE TITLE
Curl is not v7.80.0 latest version！

### ISSUE THREAD

**Issue by DroidKali** [Zackptg5/Cross-Compiled-Binaries-Android#51]
Curl in it is not the latest version of v7.80.0 at all.
It's the v7.79.1-Dev ，please update the curl version！

**Comment by Zackptg5** [comment]
Well shoot, must have messed up the version during compiling. I'll push fix tomorrow, thanks!

**Comment by Zackptg5** [comment]
Pushed to testing. Will push to master/stable tomorrow

**Comment by Dhyfer1** [comment]
@Zackptg5 curl has been updated to version [7.82.0](https://curl.se/download.html) since March 5. Please, can you update to the latest version? Thanks.

**Comment by Zackptg5** [comment]
@Dhyfer1 
Working on updating, please open new issue in the future

**Comment by Dhyfer1** [comment]
> Working on updating, please open new issue in the future

Okay, I think it was not necessary to open a new issue because this one was already there. My mistake.

**Comment by Zackptg5** [comment]
Updated :)

**Comment by Dhyfer1** [comment]
> Updated :)

Thank you very much! 😁
