### ISSUE TITLE
Add proot

### ISSUE THREAD

**Issue by wahyu6070** [Zackptg5/Cross-Compiled-Binaries-Android#52]
https://github.com/proot-me/proot

**Comment by Ayush-Singh2310** [comment]
Why not use termux proot??

**Comment by wahyu6070** [comment]
i want to make ubuntu distribution without termux

**Comment by Zackptg5** [comment]
Looks like somebody already did it for us :)
Seems pretty involved so I won't be reinventing the wheel
https://github.com/green-green-avk/build-proot-android
