### ISSUE TITLE
Stuck in bootloop

### ISSUE THREAD

**Issue by Ayush-Singh2310** [Zackptg5/Cross-Compiled-Binaries-Android#56]
Module installation works fine
But installing any binary results in bootloop.

Using Android 12 
Redmi note 8 pro(begonia)

**Comment by Zackptg5** [comment]
What are modules do you have installed? Can you grab a logcat via adb when stuck in bootloop?

**Comment by Ayush-Singh2310** [comment]
I removed the module but I'll install it again to get logcat.
Current installed modules: 
- Riru
- Riru lsposed
- Busybox for AndroidNdk
[]()M

**Comment by Zackptg5** [comment]
Try it without lsposed

**Comment by Ayush-Singh2310** [comment]
This is the log for stuck on bootlogo.
It got a little too big...

Next trying without lsposed
[logcat.txt](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/7647552/logcat.txt)

**Comment by Ayush-Singh2310** [comment]
> Try it without lsposed

Didn't work, tried with both riru and lsposed disabled and then with removed.

**Comment by Ayush-Singh2310** [comment]
Now installation working.
Only dynamic binaries cause bootloop for some reason.

**Comment by Zackptg5** [comment]
Doesn't look like it's related to this mod. Either magisk issue or rom issue by the looks of it
