### ISSUE TITLE
[Request] libwebp

### ISSUE THREAD

**Issue by SedapnyaTidur** [Zackptg5/Cross-Compiled-Binaries-Android#58]
Recently, I had a problem to view a comic that made up of animated `webp`s and a lot of browsers and android apps do not support this feature hence blank, black screen. So, I had to extract the first frame from each image. In this library, there are several commands: `cwebp`, `dwebp`, `gif2webp`, `img2webp`, `vwebp`, `webpinfo` and `webpmux`. The most important is `webpmux`. This is the needed command to extract the frame: `webpmux -get frame 1 file.webp -o output.web`. Of course I prefer them to be statics. Thanks in advance.

**Comment by Zackptg5** [comment]
[libwebp.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/7836228/libwebp.zip)
Can you give this a try? No idea if it'll work

**Comment by SedapnyaTidur** [comment]
Sorry, late to replay. I was a little busy. Yes they worked just fine even though the binaries are all dynamics, so there is no need of static libraries I think. I can understand that. Most of them require libz.so, libm.so, libdl.so, libc.so. Well I gonna close issue now.

**Comment by Zackptg5** [comment]
they ended up being dynamic? I'll need to look into that cause they should've been static
