### ISSUE TITLE
IW v5.4 here

### ISSUE THREAD

**Issue by kimocoder** [Zackptg5/Cross-Compiled-Binaries-Android#6]
Hi!

IW v5.4 and libnl3 may be added.
I've got a complete build script below

https://github.com/kimocoder/android_tools_iw

**Comment by Zackptg5** [comment]
Sweet, I'll give it a lookover, thanks!

**Comment by Zackptg5** [comment]
I've gotten it to build dynamically linked with your build script no problem but no matter what flags I pass, it doesn't compile static (always ends up dynamic). Any ideas? I only include static binaries in this repo

**Comment by Zackptg5** [comment]
Actually, scratch the above, got static linked arm and arm64 libs. x86/64 is giving me issues though

**Comment by Zackptg5** [comment]
Attached is static arm/arm64, dynamic x86/64, and the build script (modified yours - combined into 1, all setable variables at top)
[build.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5221845/build.zip)

x86 and x64 compiles for libnl stuck at "./conftest" when attempting static link compile. I have no idea why. If you're able to figure that out, I'd be happy to add iw to the repo but until then, I need all 4 of those architectures in statically compiled (I do have the latest releases of iw and libnl in here, rolling back to yours didn't change anything)

**Comment by Zackptg5** [comment]
After thinking some things over, I'm going to add dynamic linked binaries separately and so will be adding iw to it. I'm not entirely sure how I'll be doing it yet but it'll happen soon :)
Getting a static compile would be even better though for compatibility reasons

**Comment by Zackptg5** [comment]
Added dynamic linked iw to testing branch, will be pushed to master once everything's worked out within the week
