### ISSUE TITLE
busybox in /dev?

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#66]
how did busybox end up under /dev?

[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/8561785/ccbins-verbose.log)

![Screenshot_20220426-051326_Termux](https://user-images.githubusercontent.com/25366502/165268636-2e99aef5-c3d4-43e4-96de-fdb1dd158712.jpg)

**Comment by Zackptg5** [comment]
That's where magisk puts all magisk modules. It moves it to a different spot each boot for detection evasion. It's bind mounted to /system/bin

**Comment by diehard88** [comment]
@Zackptg5 

The real problem, I figured out, is the fact that android 11 removed /sbin, so busybox was installed somewhere else.

Also, the location of busybox under /dev seems to be changing after every reboot.

![]()
