### ISSUE TITLE
aria2, syncthing request

### ISSUE THREAD

**Issue by demolg** [Zackptg5/Cross-Compiled-Binaries-Android#7]

**Comment by Zackptg5** [comment]
I'll take a look at aria2 and get back to you on it

Syncthing already has an arm and arm64 compile on their site: https://syncthing.net/downloads/

**Comment by Zackptg5** [comment]
Made a build script for aria2 here: https://github.com/Zackptg5/Aria2-Android
Compiles fine, however, static link is unable to resolve url names - maybe ndk/bionic related. This repo only has static binaries in it for max device compatibility so until that's figured out (which I doubt it will be, least by me), I won't be able to include it in here. However, the dynamic ones work fine
[aria2-dynamic.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/5220059/aria2-dynamic.zip)
Attached is a zip with aria 2 dynamically linked with api of 29, so you'll need to be on android Q+. You can always clone my build repo following instructions in the readme and change the api for older devices

You may also need to create /system/etc/security/ca-certificates.crt file as well, I have a script for that in the repo too: https://github.com/Zackptg5/Aria2-Android/blob/master/ca-certificate.crt_gen.sh

Seems to work for me but I'm not 100% sure that the crt file is correct

**Comment by Zackptg5** [comment]
So after thinking it over, I'm going to add dynamic linked binaries separately and so will be adding aria2 to it. I'm not entirely sure how I'll be doing it yet but it'll happen soon :)

**Comment by Zackptg5** [comment]
Quick update, found out that the static compile works fine but requires the --async-dns flag so I'll be adding aria2 to the main repo after all

**Comment by Zackptg5** [comment]
aria2 has been added!

**Comment by demolg** [comment]
Great, thanks for you working.
