### ISSUE TITLE
Sourcing /etc/nanorc via .aliases

### ISSUE THREAD

**Issue by ohmybahgosh** [Zackptg5/Cross-Compiled-Binaries-Android#70]
To have syntax highlighting when using nano, we need to source the nanorc file which then sources all the syntax nanorc files:

### /sdcard/.aliases Before:

```bash
alias nano='nano -l'
```

### /sdcard/.aliases After:
```bash
alias nano='nano -l -f /etc/nanorc'
```

**Comment by Zackptg5** [comment]
Looks like there's actually a compile option that does this `--enable-altrcname` that does this so aliases aren't needed. There's a new version of nano out so I'll get it working either with that or the alias for the next build

**Comment by Zackptg5** [comment]
Compile option worked :)
