### ISSUE TITLE
[Question] How to implement nano in system to use it with adb?

### ISSUE THREAD

**Issue by rahaaatul** [Zackptg5/Cross-Compiled-Binaries-Android#71]
I'm trying to install nano inside my system and I have root. How do I implement nano in system so I can use it with adb to edit system files and non-system files too?

Thank you.

**Comment by Zackptg5** [comment]
If you use ccbins magisk module, you can install it through it along with my other binaries

**Comment by rahaaatul** [comment]
> If you use ccbins magisk module, you can install it through it along with my other binaries

I don't have magisk. I'm on Android Lollipop. But I have SuperSU. How can I place them inside the system?

I installed etc.zip in etc and nano-arm in etc and usr.zip in usr and gave the files 644 permission but it isn't working. Can you please help me?

**Comment by Zackptg5** [comment]
Ah, you're almost there. Any executable file (such as binaries) needs 0755 permissions. So chmod nano to 0755 and it should work as expected

**Comment by rahaaatul** [comment]
> Ah, you're almost there. Any executable file (such as binaries) needs 0755 permissions. So chmod nano to 0755 and it should work as expected (I'm also assuming you extracted the zip files?)

Yes, I did extracted and placed them according to the folder name etc & usr. And other one named nano-arm in etc folder.

**Comment by rahaaatul** [comment]
I have given `chmod 0755 nano` with termux via adb. Didn't work.

I symlinked nano to system/bin, system/xbin, tmp-mksh. And it's giving me this error:
`Error opening terminal: vt100.`

Do you know what it is?

**Comment by Zackptg5** [comment]
Ya, you got the perm right. 
Name shouldn't matter, is it in /system/bin?
Last thing to check is chcon, should be set to 
```
u:object_r:system_file:s0
```

**Comment by rahaaatul** [comment]
> Name shouldn't matter, is it in /system/bin? Needs to be there or other bin directory in the PATH
It's in /system/etc but I symlinked to bin and xbin too.

> Last thing to check is chcon, should be set to 
> ```
> u:object_r:system_file:s0
> ``` 

How do I set it like this? I'm unfamiliar with this.

**Comment by Zackptg5** [comment]
> > Name shouldn't matter, is it in /system/bin? Needs to be there or other bin directory in the PATH
> 
> It's in /system/etc but I symlinked to bin and xbin too.
> 
> > Last thing to check is chcon, should be set to
> > ```
> > u:object_r:system_file:s0
> > ```
> 
> How do I set it like this? I'm unfamiliar with this.

It'd be best in /system/bin and it'd be chcon

**Comment by rahaaatul** [comment]
I looked into the nano file of osm0sis in bin and it is something called wrapper:

```
#!/system/bin/sh
# nano: wrapper to set up and run nano from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

if [ "$1" == "--term" ]; then
  term=$2;
  shift 2;
else
  term=screen;
fi;

clear;
resize >/dev/null 2>&1;
TERMINFO=$dir/../etc/terminfo TERM=$term $dir/nano.bin "$@";

```
I do not understand any of this, I hope you can help me with this. 

Also, can I create this wrapper myself? For example, to use your cross compiled **vim** from adb shell.

**Comment by Zackptg5** [comment]
Ya. I recommend doing the following:
Remove all of my stuff.
Flash osm0sis's nano-ndk zip
Replace his nano.bin with my nano binary (rename it to nano.bin as well)
Then add in my other files

Should be the most surefire way of getting it installed properly

**Comment by rahaaatul** [comment]
> Ya. I recommend doing the following:
> Remove all of my stuff.
> Flash osm0sis's nano-ndk zip
> Replace his nano.bin with my nano binary (rename it to nano.bin as well)
> Then add in my other files
> 
> Should be the most surefire way of getting it installed properly

It actually worked! All I needed was the wrapper and Terminfo folder from nano-ndk repo.

And I did the same thing with vim. Now if I call it, it first gives a error:
```
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```
I hit enter, and it works. Do you know what the error is?

**Comment by Zackptg5** [comment]
Did you install the usr folder with the vim scripts and such in it?

**Comment by rahaaatul** [comment]
> Did you install the usr folder with the vim scripts and such in it?

Yes. I gave all files 644 permission and all folders 755 permission.

Also, I double checked, there's the file called defaults.vim.

**Comment by Zackptg5** [comment]
Hmm, haven't run vim in a while but looks like it does that for me too. Must have been something with one of the recent updates. Can you open a new issue with the bug report?

**Comment by rahaaatul** [comment]
Done #74.

**Comment by rahaaatul** [comment]
> Can you open a new issue with the bug report?

Done! #74.
