### ISSUE TITLE
ffmpeg, nonfree + other goodness.

### ISSUE THREAD

**Issue by eladkarako** [Zackptg5/Cross-Compiled-Binaries-Android#73]
didn't find many guides for nonfree,  
some targeting raspberry-pi might be helpful,  
and there might be docker with patches such as https://github.com/nanake/ffmpeg-tinderbox/releases (but, for arm/arm64).  
eventually I've just used some assets from an apk..  
(see https://github.com/Magisk-Modules-Repo/ccbins/issues/7 )  

feel free to update here, if you've got nice guides with as much as non-free libs as possible :]

**Comment by Zackptg5** [comment]
Looking like a lot of dependencies for this one (lots of other libs to cross compile). No guarantee I'll be able to get it but I'll keep this updated with my progress (it'll likely be some time)

**Comment by Zackptg5** [comment]
Gave it several attempts but wasn't able to get it to cross compile. There's a ton of lib dependencies as well for it further complicated things. Sorry!
