### ISSUE TITLE
[Vim] Failed to source defaults.vim

### ISSUE THREAD

**Issue by rahaaatul** [Zackptg5/Cross-Compiled-Binaries-Android#74]
# The Bug
Opening file with vim gives this error:
```
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

# Reproduce The Bug
Open any file with vim:
`vim /path/to/file`

# Expected Behavior
Open the file without E1187 error.

# Device Info
 - Android TV 5.1
 - SuperSu 2.82
 - Manually placed vim files, Correct permissions given

**Comment by Zackptg5** [comment]
Looks like it's not an issue with the binary itself but with environmental variables. Needs VIM and VIMRUNTIME set to correct directories. Not sure why it wasn't needed before but is now but I didn't see any good way to set it during compile. I'll be pushing updated vim anyways and I'll push update to the service script that writes the aliases shortly

**Comment by Zackptg5** [comment]
Fixed in 4266e98aaa2da499cddab07577ef243943a8bb76

**Comment by Zackptg5** [comment]
@rahaaatul Figured out how to set the variables in the binary itself. Just use the ones here and you won't have to worry about aliases or anything: ed1c0ebcda0ea76965b0fb6a1ed89467ee3e0e20

**Comment by rahaaatul** [comment]
> @rahaaatul Figured out how to set the variables in the binary itself. Just use the ones here and you won't have to worry about aliases or anything: ed1c0ebcda0ea76965b0fb6a1ed89467ee3e0e20

Definitely working! Nice work man! 

Is there a openSSH binary you would add to your compile binary collection to connect via terminal from Android to Android TV? I heard it's better than adb.
Also, Would you update nano to 6.4? Doesn't really matter to me, just asking.

And also, nano and vim is working for me is because of terminfo I copied from osm0sis's repo. I call that in terminal, and that calls your binary. Would you directly add it in your repo also?

Thank you. Couldn't have worked it without your help. 🙏

**Comment by Zackptg5** [comment]
No idea about openssh, best to open a feature request for that binary.
Terminfo files can be found on ncursesw in this repo. You may need to set TERMINFO environment variable too to /system/usr/share/terminfo
