### ISSUE TITLE
OpenSSH

### ISSUE THREAD

**Issue by rahaaatul** [Zackptg5/Cross-Compiled-Binaries-Android#75]
Basically I want to enable [OpenSSH](https://www.openssh.com/) server in my Android TV. Here is the [release page](https://www.openssh.com/releasenotes.html).

**Comment by Zackptg5** [comment]
Pushed test build to testing branch if you can try it out and let me know how it works. (Type 99 in ccbins to switch to testing branch)

**Comment by zebrapurring** [comment]
Why was OpenSSH removed (3ab43060d6d145728ae18f53465446aaf13c2ad8)?

Should this issue be re-opened?

**Comment by Zackptg5** [comment]
It wasn't functional and had a lot of dependencies which I don't have the time to figure out. Termux has openssh that works fine. I doubt I'll have time in the near future either which is why I closed it
