### ISSUE TITLE
No recovery after install

### ISSUE THREAD

**Issue by comradekingu** [Zackptg5/Cross-Compiled-Binaries-Android#76]
Upgraded to v9_2-14 of of this module and [USB Samplerate Unlocker](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker) (at the same time) from Fox mmm.
This left me with only the bootloader available after the reboot, since neither normal boot or recovery works.
That also means I can't get adb access to remove modules?

The camera stopped working beforehand (possibly also due to the protection for use that I forget the name of) so not ruling out general corruption.

Moto G7 Power (Ocean) XT1955-4

    LineageOS 17.1
        Magisk 24.1?
    Some other modules installed. Bootloop protection, some font thing, etc.

Can I reflash TWRP, or the rom without deleting user data to fix this?
Help much appreciated :)

Also posted this in https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/issues/2

**Comment by Zackptg5** [comment]
This module doesn't touch boot or recovery. It only exists in /data partition, magisk bind mounts it over system and/or vendor during the boot process so it'd be unaffected by a dirty flash

**Comment by comradekingu** [comment]
Didn't find anything untowards in the logs. Anything in particular that could indemnify this module?
Installed the newest TWRP available for the device (3.5.2_10.0) and wiping Dalvik booted up LineageOS again.
That also removes root.
Maybe some race-condition of installing the two at the same time?

**Comment by Zackptg5** [comment]
Only potential thing I could think of is a binary overwriting an existing one when mounted with a different expected behavior. I can't think of any specifically that would do that that I haven't already addressed to prevent that from happening. I don't know anything about the other module
