### ISSUE TITLE
coreutils cp size bug

### ISSUE THREAD

**Issue by knightrider-kit** [Zackptg5/Cross-Compiled-Binaries-Android#79]
**Describe the bug**
When copying files using -g flag goodbye report doubles size of transferred file(s).

**To Reproduce**
Copy any file using -g flag.

**Expected behavior**
File will be copied with final report describing proper amount of data copied.

**Screenshots**

**Device Info (please complete the following information):**
 Android 17 (Jellybean 4.2) - rooted

**Additional context**

**Comment by Zackptg5** [comment]
Do you have any other android devices you can test it on? I'm unable to replicate that bug on my devices but I don't have any jellybean devices.

**Comment by knightrider-kit** [comment]
I have several of these same devices that I experiment with but nothing
else unfortunately. Interestingly, I have tested on several devices now and
the bug turns up in all but one. I attempted to compile the cp program
before using
https://github.com/JohnFawkes/Coreutils-Advcpmv-For-Android-Build-Script in
a chroot ubuntu build environment on one of these devices and it worked
until I closed down the chroot environment at which point I kept getting
the error of "failed to run" du and find which I tracked down to the popen
function not working. The device of mine that the bug does not exist on is
the same one in which I have the chroot environment but it works fine even
without that loaded. I have been pouring over it all morning trying to
discover if I had modified any libs in the pure android environment but
have not been able to discover one. Admittedly, these are old devices and I
am just a fledgling programmer so the bug is probably not that important
but thanks for your time and consideration in the matter.

**Comment by Zackptg5** [comment]
I'd recommend trying my build script in this repo, it's most up-to-date with patches and what not. I tested it on manjaro build environment, don't know about ubuntu

It requires lollipop or higher api to compile, but static complied binary should run on any android device in theory which is why I was wondering if this was only happening on older than lollipop devices.

Which terminal app were you using? Any other mods installed?

**Comment by Zackptg5** [comment]
With no way of testing, I have no way of fixing. Sorry
