### ISSUE TITLE
install location

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#8]
the install location is /system/bin.

however, the binaries are installed in /sbin/.magisk/modules/ccbins/system/bin.

did I miss something?

thank you.

**Comment by KaMyKaSii** [comment]
Magisk don't real add/overwrite files in /system, just bind mount the files there, so you can call the binaries from /system/bin

**Comment by Zackptg5** [comment]
This is how magisk mount works. The actual files are stored in sbin (or dev if android 11) and bind mounted at boot
