### ISSUE TITLE
mod-util.sh version

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#81]
the version of mod-util.sh found in your repository is the following:

```
# Versions
MODUTILVER=v2.6
MODUTILVCODE=262
```

while the latest version by veez21 is lower:

```
# Versions
MODUTILVER=v2.6.1
MODUTILVCODE=261
```

thank you.

**Comment by Zackptg5** [comment]
They're the same other than some minor changes I've made. Versioning got screwed up at some point along the way and downgrading the numbers to match would mess with things so I'm just keeping them as is. Thanks!
