### ISSUE TITLE
/sbin

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#83]
google removed /sbin in android 11.

why is it still being referenced in PATH?

![](https://i.imgur.com/BzoYcAr.jpg)

**Comment by johnt1989** [comment]
That's not cabins, that's due to using the command su in termux open the file su located @ 
/data/data/com.termux/files/usr/bin/su
This changes your path, you can change it here or inside the module terminal modifications by using unset, path .... etc...

**Comment by Zackptg5** [comment]
I also don't recommend using ccbins with termux. Termux has its own environment which doesn't always play nice with ccbins, plus just about everything in ccbins already has termux packages for it
