### ISSUE TITLE
[Request] freedup

### ISSUE THREAD

**Issue by ildar** [Zackptg5/Cross-Compiled-Binaries-Android#87]
**freedup**
really handy tool for reclaiming space.
URL of source code: http://freedup.org/
Thanks in advance.

**Comment by Zackptg5** [comment]
I might be able to cross-compile this but I don't think using this would be a good idea on android. Definitely wouldn't recommend for main system/vendor/product etc. partitions. Could potentially be useful for data but this could also go poorly if the "real" copy is in an app you uninstall and the other apps just have dead symlinks and that's assuming you don't run into problems do to different mounting types used.
All of this is assuming you're not using magisk which would make things even more complicated

**Comment by ildar** [comment]
emm, yes, of course one can fall into many pitfalls with any program.
Yet command line utils are known as good tools for those who know what
they are doing.
Regarding the Android context: no, `freedup` does not deal with
symlinks. It just finds the same files and replace them with
hard-links to the one and only copy. This helps preserving space which
is crucial for this type of devices.
The only possible pitfall here is when a user/app changes a file and
the side effect should be that the file changed for all the hardlinks.
Yet, again, this should be very rare. Only for those who know what
they're doing.

**Comment by Zackptg5** [comment]
Added freedup. Can you test it out to make sure it works as expected?
[freedup.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11234668/freedup.zip)

**Comment by ildar** [comment]
Thanks a lot.
I tested it and it works as usual.
Thanks again.

**Comment by Zackptg5** [comment]
Awesome! Merged in #95
