### ISSUE TITLE
ccbins errors read-only folders

### ISSUE THREAD

**Issue by j03ll0b0** [Zackptg5/Cross-Compiled-Binaries-Android#89]
Fresh install Android 13, vendor erofs, installed ccbins through foxmmm, and called ccbins and shows several errors about read-only folders and TMP folder not found.

================================
Cross Compiled Binaries v9.2(14)
by Zackptg5
================================
BusyBox v1.34.1-osm0sis
/dev/hyloogble/.magisk/modules/ccbins/busybox
================================

Testing internet connection [/] - OK

Fetching available binaries
rm: can't remove '/dev/hyloogble/.magisk/modules/ccbins/.checksums': Read-only file system
 [/]touch: /dev/hyloogble/.magisk/modules/ccbins/dlerror: Read-only file system
Download error for /dev/hyloogble/.magisk/modules/ccbins/.binaries!
 [-]touch: /dev/hyloogble/.magisk/modules/ccbins/dlerror: Read-only file system
Download error for /dev/hyloogble/.magisk/modules/ccbins/.binaries-dynamic!
 [\] - Done

Checking for mod updates
 [-]touch: /dev/hyloogble/.magisk/modules/ccbins/dlerror: Read-only file system
Download error for /dev/hyloogble/.magisk/modules/ccbins/.changelog!
 [/] - Ccbins is up to date

Checking for binary updates
 [/]touch: /dev/hyloogble/.magisk/modules/ccbins/dlerror: Read-only file system
Download error for /dev/hyloogble/.magisk/modules/ccbins/tmp!
 [-]cat: can't open '/dev/hyloogble/.magisk/modules/ccbins/tmp': No such file or directory
 - Installing NCursesw v
mv: can't rename '/dev/hyloogble/.magisk/modules/ccbins/tmp': Read-only file system
 [-]touch: /dev/hyloogble/.magisk/modules/ccbins/dlerror: Read-only file system
Download error for /dev/hyloogble/.magisk/modules/ccbins/system/ncursesw.zip!
unzip: can't open /dev/hyloogble/.magisk/modules/ccbins/system/ncursesw.zip[.zip]
 - NCursesw has been installed!
 [|] - Binaries are up to date

Checking for conflicting modules
 [\] - No conflicting mods were found

================================
Binary Installer ===============
================================
Current install location: /system/bin
Auto-update binaries at launch: Enabled (recommended)
DOH Server: None
================================
Choose option ==================
================================
0: Refresh CCbins (remove everything - start fresh)
1: General Information
2: Options/Settings
3: List all installed binaries
4: List all downloadable binaries
5: Remove binary
6: Install binary
7: Install dynamic linked binary
Type 'q' at any time to quit
-->

 - Rom Arrow OS 13 vendor Q
 - Magisk version v26001
 - kuroneko kernel 1133, vendor, erofs

adb and nano ndk work just fine.

**Comment by Zackptg5** [comment]
Can you post the log file: /data/local/tmp/ccbins.log?

**Comment by j03ll0b0** [comment]
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11183959/ccbins-verbose.log)

**Comment by Zackptg5** [comment]
Looks like magisk module directories are mounted as ro now, I'll looks for a workaround and update here with any progress

**Comment by j03ll0b0** [comment]
I've communicated to the groups in telegram and it's an expected behavior of Android Q roms, furthermore I've used the the build from actions section so it might be just that since I went back to Android R vendor and now I'm having issues with apps selecting the downloads folder, so I'm gonna start over and use normal release APK, I've tried ccbins in R and it also was RO so I mount -o remount,rw without much issues and everything went just as expected, i enjoy very much being able to use your work and thank you for that. Regards.

**Comment by Zackptg5** [comment]
So I think this has given me an opportunity to add a feature I've wanted for a while now: live mounting/unmounting. It'll only be for magisk 26+ though.

So I'm going to update ccbins in it's current itteration one more time and set main files to offline - this'll be renamed to ccbins_legacy. It'll work just like the current version and be for magisk version < 26. It'll still pull all updated binaries so should work completely fine in the foreseeable future, it won't be updated anymore.

Current ccbins will be updated for magisk 26+ only and will use tmpfs magisk mounting for live mounting/unmounting. Only reboot will be for initial ccbins install and then you'll never need to reboot again for it

**Comment by j03ll0b0** [comment]
Great news, can't wait to test your updated ccbins with the new magical v26. Thanks again for your work. Awesome project and very useful.

**Comment by Zackptg5** [comment]
Fixed in commit #91

**Comment by diehard88** [comment]
it works.

thank you!
