### ISSUE TITLE
checksum failure after updating to magisk 26

### ISSUE THREAD

**Issue by diehard88** [Zackptg5/Cross-Compiled-Binaries-Android#90]
![Screenshot_20230410-182905_Termux](https://user-images.githubusercontent.com/25366502/231012211-c6907524-0030-4e87-b780-fc7bcfd52274.jpg)

[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11194523/ccbins-verbose.log)

**Comment by Zackptg5** [comment]
I'll need to test it with magisk v26. There were a lot of under the hood changes so possible something broke
