### ISSUE TITLE
Adding adb and rsync

### ISSUE THREAD

**Issue by nibirrayy** [Zackptg5/Cross-Compiled-Binaries-Android#96]
Can you please add adb and rsync binaries as well. i think it will be quite useful if we could use another phone with adb to fix a phone is bootloop.

Rsync
https://github.com/ribbons/android-rsync

Adb
https://github.com/Magisk-Modules-Repo/adb-ndk

**Comment by Zackptg5** [comment]
I'll definitely look into it and update this with where I'm at

**Comment by Zackptg5** [comment]
@nibirrayy 
[rsync.zip](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11290763/rsync.zip)
Can you test these out and let me know if they work completely?

**Comment by nibirrayy** [comment]
The binary seems to work. I just dumped it on my `/sdcard` and tried running it. It worked. Haven't tried the helper script in the zip but surely it will work as it is written in bash. 

Still have to test the rsync binary to sync files.
Just in the middle to migrating data from my old phone to my new phone so give me a day or 2, will test it asap

**Comment by Zackptg5** [comment]
Sweet, added rsync to main ccbins in pull #97

**Comment by Zackptg5** [comment]
I don't think adb will happen. I'm not seeing any standalone source code for compile, all built into android itself by the looks of it. I'd recommend to keep using osm0sis'
