### ISSUE TITLE
sqlite3 libz.so error

### ISSUE THREAD

**Issue by j03ll0b0** [Zackptg5/Cross-Compiled-Binaries-Android#98]
When installing ccbins dynamic binaries there is an error displayed when sqlite3 get copied into installation folder.

Just download and install on fresh system.

![Screenshot_20230502-083857_Termux](https://user-images.githubusercontent.com/104862685/236096514-9cdd8866-bfbc-4157-9da6-5c6db79223af.png)

Redmi 9A
CrDroid9.2 (vendor Q) A13
Magisk v26.1

**Comment by j03ll0b0** [comment]
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11527522/ccbins-verbose.log)
I'll report how it went calling ccbins after reboot

**Comment by j03ll0b0** [comment]
![Screenshot_20230502-083857_Termux](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/assets/104862685/ba2f1b9c-c736-4b90-bb23-6288a7fc83f7)
I did a removal and then installed again, got that error, removed sqlite3, that's all.

**Comment by j03ll0b0** [comment]
I did a clean install this time, removing the offending rvx_yt before everything else, here is the ccbins-verbose.log
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11559831/ccbins-verbose.log)
Thanks, hope this helps, lemme know if you might need anything else in other to bring this to boil.

**Comment by Zackptg5** [comment]
It appears to be an empty file on my end.
Let's try this:
Run ccbins
Choose option 0 (Reset ccbins)
exit out off ccbins
Run ccbins again
Install sqlite
Exit ccbins
Obtain the log file and post

The log file is only for the last time you ran ccbins, it'll then get overwritten the next time you run it

**Comment by j03ll0b0** [comment]
I followed your instructions, it didn't show any errors, here's the log file. Thanks a lot for your work.
[ccbins-verbose.log](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/files/11615223/ccbins-verbose.log)

**Comment by j03ll0b0** [comment]
I've moved forward to vendor R in my device, setup a new ROM with Android 13, and used the magisk from release section, installed ccbins and went one by one on the install process, found error only with SQLite, the same error, but everything seems to work, I'm just going to ignore it from now on
